### ISSUE TITLE
Pylint gets confused: No name 'path' in module 'path'

### ISSUE THREAD

**Issue by nedbat** [jaraco/path.py#102]
Pylint doesn't understand that path.py defines the name "path".  It does so with the @alias decorator, which is only used once in the file.  So there are six extra lines of code to define a decorator which only serves to confuse pylint.

Would you mind getting rid of the decorator and replacing it with ``path = Path``?  Then pylint will understand.

**Comment by sarina** [comment]
:+1:

**Comment by chrisidefix** [comment]
This latest fix (release 8.0) breaks compatibility with other packages using path.py (in particular `pickleshare`, which is used in ipython / jupyter). I had to revert to release 7.7.1 for now to get ipython working again.

It looks like `pickleshare` uses `path.py` like this: `from path import path as Path` and may need to be updated now, but I thought anyone else who has this problem might wanted to know.

```
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/usr/local/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python2.7/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.core.interactiveshell import DummyMod
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 31, in <module>
    from pickleshare import PickleShareDB
  File "/usr/local/lib/python2.7/site-packages/pickleshare.py", line 41, in <module>
    from path import path as Path
ImportError: cannot import name path
```

**Comment by nedbat** [comment]
Wow, this isn't what I was hoping for at all.  Why break the public interface of the package?

**Comment by ViktorAtD2L** [comment]
Well, it was broken around a major release boundary, so one could say at least this wasn't done with a 7.8.0 release. But still, I've had to revert back to 7.7.1 as well, as tools I need depend on the previous public interface.

**Comment by jaraco** [comment]
The intention has been to remove the deprecated `path` name since the 6.2 release, which was made almost a year ago, so this change was planned. The presence of the `alias` was to make the `path` name easily visible alongside the canonical `Path` declaration, rather than burying it near the end of the file.

The client libraries should be able to require `path.py >= 6.2` and change their imports to reference the preferred name.

**Comment by whitmo** [comment]
is keeping path = Path really that big a deal? this change just broken a huge amount of code we are running here at canonical. :crying_cat_face: :person_frowning:

**Comment by Nodd** [comment]
@whitmo :+1: 
"almost one year ago" isn't very far in the past for lots of codebases. Given that a simple `path = Path` keeps back compatibility, it seems logical to keep it. A big warning in the documentation would be useful too.

**Comment by jaraco** [comment]
Fair enough.

**Comment by chuckbutler** [comment]
@jaraco are we going to see a backwords compat release hit pypi? This is effecting by and large about 30 projects that I'm aware of here in the Juju ecosystem alone, I'm willing to bet it spins much larger when you start looking at other tools we're using.

**Comment by jaraco** [comment]
I've pulled 8.0 from PyPI

**Comment by chuckbutler** [comment]
Thanks! We'll start going through and pinning our dependencies so its far less of an impact when design decisions like this surface in the future.  Thanks for the rapid response @jaraco

**Comment by codewarrior0** [comment]
IPython 4.0.0 (and previous) will do `from path import *` which doesn't work with 8.1 since `path` isn't in `__all__`. It also declares `path.py` as a requirement without pinning a version, so running `pip install ipython` on a clean install will give you a broken `ipython`

I'm going to pin 7.7.1 in my project now as a workaround.

**Comment by asampat3090** [comment]
@codewarrior0 could you specifically show how you did this? I tried to reinstall 7.7.1 for path.py but pickleshare still has an error. Is there a specific version I should be using for pickleshare?

**Comment by codewarrior0** [comment]
I don't know about pickleshare. I may have been wrong about IPython 4.0.0, as it doesn't seem to be broken on a clean install - but IPython 3.2.1 certainly is.

**Comment by codewarrior0** [comment]
Here's what I did to get a broken IPython:

```
$ virtualenv ipytest
$ . ipytest/scripts/activate
$ pip install ipython==3.2.1
$ ipython
[...]
ImportError: cannot import name path
```

And this is what it took to fix it:
```
$ pip install py.path==7.7.1
$ ipython
[...]
IPython 3.2.1 -- An enhanced Interactive Python.

In [1]:
```

**Comment by asampat3090** [comment]
Cool thanks! Worked for me. Definitely looking forward to a fix in IPython 4.0.0.

**Comment by BhavyaBibi** [comment]
i also have this problem. in follows this command that is clear it
 python -m pip install pylint
thats problem will be clear in just close cmd command in vs code. Then python is reload the problem will solve it

**Comment by jaraco** [comment]
Hi @BhavyaBibi, this issue is very old. If you're still having an issue, please report it in a separate issue. Please be sure to indicate which commands you ran with what Python version and OS and what output you got and what output you expected.
